<a href="https://colab.research.google.com/github/ashutoshb206/Hackathon_iitg/blob/main/Hackathon_iitg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df_test = pd.read_csv('hacktest.csv')
df = pd.read_csv('hacktrain.csv')

In [4]:
df.describe()

,Unnamed: 0,ID,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
count,8000.000000,8000.000000,7440.000000,6800.000000,7200.000000,7040.000000,7520.000000,6880.000000,7280.000000,6640.000000,...,7520.000000,7280.000000,7120.000000,6240.000000,7360.000000,6880.000000,6560.000000,7440.000000,6800.000000,7600.000000
mean,4984.202625,4985.202625,5845.476916,4868.091395,4469.837748,5193.485086,2927.586705,4924.493648,3313.881373,4987.520158,...,4872.681670,3674.886731,3012.178524,3055.167358,2041.316792,2799.820342,2144.360224,6259.064275,2629.203972,2578.449870
std,2900.022898,2900.022898,2261.409128,2758.499942,2876.218394,2510.389832,2728.325670,2600.418802,2434.828743,2674.963286,...,2776.135418,2331.105635,2068.334108,2209.985887,2040.354512,2452.563243,2267.606759,1825.563702,2386.147667,2436.270797
min,0.000000,1.000000,-433.735000,-1781.790000,-2939.740000,-1924.360000,-1794.870000,-1848.910000,-1574.970000,-2532.490000,...,-2683.600000,-1043.160000,-2435.900000,-1505.780000,-1445.370000,55.564100,-232.292000,-2729.430000,-2139.860000,-4145.250000
25%,2514.750000,2515.750000,4331.232500,2067.265000,1521.195000,3087.072500,500.515750,2398.385000,992.778250,2404.075000,...,2010.732500,1369.355000,1368.742500,1009.827500,419.987000,791.741250,501.602750,5938.257500,691.171500,689.199000
50%,4917.500000,4918.500000,6908.255000,5513.375000,4672.000000,5810.755000,1586.240000,5742.485000,2802.010000,5831.120000,...,5484.905000,3659.770000,2633.695000,2624.125000,1183.715000,1599.385000,969.711500,6941.010000,1521.210000,1439.950000
75%,7311.250000,7312.250000,7626.845000,7555.570000,7431.697500,7511.880000,5703.067500,7280.110000,5508.350000,7430.915000,...,7607.755000,5927.035000,4128.082500,4952.317500,3075.997500,4909.997500,3227.380000,7395.612500,4452.257500,4146.342500
max,10544.000000,10545.000000,8376.150000,8566.420000,8650.500000,8516.100000,8267.120000,8499.330000,8001.700000,8452.380000,...,8489.970000,7981.820000,8445.410000,7762.980000,8078.080000,8216.700000,8247.630000,8410.330000,8418.230000,8502.020000

In [5]:
df_test.describe()

,Unnamed: 0,ID,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
count,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,...,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000,2845.000000
mean,1422.000000,1423.000000,5285.311732,4524.020744,3970.782482,4619.879362,2650.444746,4707.699198,3399.498607,4547.764233,...,4372.211461,3507.372651,3029.266553,2944.609166,2004.551484,2348.475869,1786.190268,5562.937183,2388.282039,2529.853365
std,821.425083,821.425083,2375.641035,2683.209632,2835.736587,2545.021404,2498.047435,2617.748386,2455.988128,2828.650853,...,2685.492110,2211.572661,2053.854976,2132.625853,1935.035216,2218.498698,2003.596912,2414.344589,2234.440944,2418.944853
min,0.000000,1.000000,-3363.640000,-3345.120000,-5774.370000,-5355.400000,-3232.180000,-5992.080000,-3520.840000,-5604.450000,...,-3991.910000,-3257.730000,-4869.010000,-4212.560000,-2853.890000,-4354.630000,-106.117000,-6807.550000,-4550.190000,-4723.980000
25%,711.000000,712.000000,3277.960000,2080.930000,1251.970000,2629.150000,584.177000,2353.060000,1070.800000,1971.150000,...,1812.710000,1495.400000,1482.540000,1052.600000,460.419000,702.187000,478.272000,4460.340000,678.423000,654.996000
50%,1422.000000,1423.000000,6089.850000,4776.980000,3755.380000,4763.230000,1556.290000,5295.060000,3202.980000,5117.820000,...,4571.050000,3391.960000,2778.340000,2727.780000,1398.370000,1340.560000,857.606000,6523.100000,1427.090000,1554.730000
75%,2133.000000,2134.000000,7370.970000,7107.910000,6704.870000,6949.620000,4550.290000,7114.520000,5557.170000,7217.340000,...,6988.020000,5411.160000,4380.210000,4571.120000,2765.040000,3510.240000,2160.030000,7289.490000,3800.560000,4195.840000
max,2844.000000,2845.000000,8377.720000,8533.770000,8527.390000,8501.490000,8211.380000,8416.930000,7954.460000,8439.350000,...,8480.190000,7797.990000,8430.740000,7919.070000,8206.780000,8235.400000,8197.020000,8388.040000,8363.950000,8261.640000

In [6]:
df

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,...,NaN,-1043.160,-1942.490,267.138,NaN,NaN,211.328,-2203.020,-1180.19,433.906
1,1,2,water,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,...,NaN,-933.934,-625.385,120.059,364.858,476.972,220.878,-2250.000,-1360.56,524.075
2,3,4,water,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,...,-1025.880,368.622,NaN,-1227.800,304.621,NaN,369.214,-2202.120,NaN,-1343.550
3,4,5,water,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,...,-1813.950,155.624,NaN,-924.073,432.150,282.833,298.320,-2197.360,NaN,-826.727
4,7,8,water,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.650,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,...,1117.740,1176.600,1044.110,NaN,369.082,465.843,362.882,979.795,NaN,433.659
7996,10538,10539,impervious,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,...,984.634,2128.970,1379.660,NaN,762.633,485.204,446.724,771.747,1589.06,506.936
7997,10541,10542,impervious,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.000,1818.650,2501.72,1247.770
7998,10542,10543,impervious,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,NaN,3759.710,NaN,388.346
7999,10544,10545,impervious,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,...,7352.570,3289.860,3729.150,1994.980,NaN,5299.900,NaN,5983.130,1249.71,2424.230

In [7]:
df.isnull().sum()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64

In [8]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [9]:
df.isnull().sum()

Unnamed: 0    0
ID            0
class         0
20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
dtype: int64

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [11]:
#drop id column
df.drop(columns='ID',inplace=True)

In [12]:
df.head(3)

,Unnamed: 0,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,water,637.5950,658.668,-1882.030000,-1924.36,997.904000,-1739.990,630.087000,4987.520158,...,4872.68167,-1043.160,-1942.490000,267.138,2041.316792,2799.820342,211.328,-2203.02,-1180.190000,433.906
1,1,water,634.2400,593.705,-1625.790000,-1672.32,914.198000,-692.386,707.626000,-1670.590000,...,4872.68167,-933.934,-625.385000,120.059,364.858000,476.972000,220.878,-2250.00,-1360.560000,524.075
2,3,water,58.0174,-1599.160,4469.837748,-1052.63,2927.586705,-1564.630,3313.881373,729.790000,...,-1025.88000,368.622,3012.178524,-1227.800,304.621000,2799.820342,369.214,-2202.12,2629.203972,-1343.550

In [13]:
# class columns is categorical {Water, Impervious, Farm, Forest, Grass, Orchard}
# so we will convert it into labels
label_encoder = LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])

In [14]:
df['class']

0       5
1       5
2       5
3       5
4       5
       ..
7995    3
7996    3
7997    3
7998    3
7999    3
Name: class, Length: 8000, dtype: int64

In [15]:
label_encoder.classes_

array(['farm', 'forest', 'grass', 'impervious', 'orchard', 'water'],
      dtype=object)

In [16]:
# now spliiting into features and target
x = df.drop(columns=['class'])
y = df['class']

In [17]:
x

,Unnamed: 0,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,637.5950,658.668000,-1882.030000,-1924.360000,997.904000,-1739.990000,630.087000,4987.520158,-1325.640000,...,4872.68167,-1043.160,-1942.490000,267.138000,2041.316792,2799.820342,211.328000,-2203.020,-1180.190000,433.906
1,1,634.2400,593.705000,-1625.790000,-1672.320000,914.198000,-692.386000,707.626000,-1670.590000,-1408.640000,...,4872.68167,-933.934,-625.385000,120.059000,364.858000,476.972000,220.878000,-2250.000,-1360.560000,524.075
2,3,58.0174,-1599.160000,4469.837748,-1052.630000,2927.586705,-1564.630000,3313.881373,729.790000,-3162.140000,...,-1025.88000,368.622,3012.178524,-1227.800000,304.621000,2799.820342,369.214000,-2202.120,2629.203972,-1343.550
3,4,72.5180,4868.091395,380.436000,-1256.930000,515.805000,-1413.180000,-802.942000,683.254000,-2829.400000,...,-1813.95000,155.624,3012.178524,-924.073000,432.150000,282.833000,298.320000,-2197.360,2629.203972,-826.727
4,7,1136.4400,4868.091395,4469.837748,1647.830000,1935.800000,4924.493648,2158.980000,4987.520158,1242.870000,...,1535.00000,1959.430,-279.317000,-384.915000,-113.406000,1020.720000,1660.650000,-116.801,-568.050000,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,1207.7000,984.620000,4469.837748,1166.250000,937.478000,1072.700000,823.896000,943.698000,944.619000,...,1117.74000,1176.600,1044.110000,3055.167358,369.082000,465.843000,362.882000,979.795,2629.203972,433.659
7996,10538,2170.3500,1419.720000,1361.000000,1478.710000,983.911000,1262.110000,1422.860000,1401.970000,1372.680000,...,984.63400,2128.970,1379.660000,3055.167358,762.633000,485.204000,446.724000,771.747,1589.060000,506.936
7997,10541,1895.6800,1454.740000,4469.837748,1033.560000,1930.380000,1057.150000,1471.600000,4987.520158,2693.630000,...,888.40800,2093.020,1232.110000,1190.830000,1441.460000,1170.880000,1095.000000,1818.650,2501.720000,1247.770
7998,10542,3465.7400,1283.320000,413.412000,4391.050000,1146.820000,4473.050000,1614.750000,770.469000,4320.961814,...,5833.76000,4047.320,4515.800000,433.177000,277.296000,744.143000,2144.360224,3759.710,2629.203972,388.346
7999,10544,6941.1900,1667.870000,5084.780000,5193.485086,1588.950000,5978.190000,3313.881373,3068.030000,6471.470000,...,7352.57000,3289.860,3729.150000,1994.980000,2041.316792,5299.900000,2144.360224,5983.130,1249.710000,2424.230

In [18]:
y

0       5
1       5
2       5
3       5
4       5
       ..
7995    3
7996    3
7997    3
7998    3
7999    3
Name: class, Length: 8000, dtype: int64

In [19]:
#train_test spillting


x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y)

In [20]:
# Fit multinomial logistic regression
model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=100
)
model.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [21]:
# Predict on test set
y_pred = model.predict(x_test)

In [22]:
y_pred

array([1, 1, 3, ..., 1, 1, 1])

In [23]:
# Classification report with all original class labels
print(classification_report(
    y_test,
    y_pred,
    labels=list(range(len(label_encoder.classes_))),
    target_names=label_encoder.classes_
))

              precision    recall  f1-score   support

        farm       0.78      0.79      0.79       168
      forest       0.98      0.99      0.98      1232
       grass       0.60      0.46      0.52        39
  impervious       0.76      0.84      0.80       134
     orchard       1.00      0.17      0.29         6
       water       1.00      0.52      0.69        21

    accuracy                           0.93      1600
   macro avg       0.85      0.63      0.68      1600
weighted avg       0.93      0.93      0.93      1600

In [24]:
df_test

,Unnamed: 0,ID,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,7466.4200,413.162,5761.000,5625.45,489.4030,3923.84,3097.110,6766.42000,...,801.184,927.115,4704.14,6378.42,340.949,2695.5700,527.268,4736.75,601.843,6639.760
1,1,2,7235.2600,6037.350,1027.560,6085.14,1618.0500,6668.54,2513.990,1051.69000,...,5533.470,5103.040,5216.12,4885.27,4366.790,1234.1400,3298.110,6942.68,1070.440,842.101
2,2,3,7425.0800,6969.980,1177.940,7408.93,861.0610,7644.43,814.458,1504.29000,...,1981.390,6204.540,7021.69,5704.41,4897.450,1789.9900,2206.100,6928.93,1036.560,831.441
3,3,4,7119.1200,1731.620,6311.930,6441.61,465.9790,7128.42,1649.120,6935.22000,...,959.344,5794.150,1045.57,5572.90,586.287,685.9060,1287.000,6734.72,824.584,6883.610
4,4,5,7519.5500,8130.260,1482.540,7879.53,1001.2100,7937.60,4122.530,1094.51000,...,7636.070,6996.760,7413.43,4596.13,4511.700,1413.5200,3283.940,7937.68,1857.800,1336.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,2840,2841,-1673.7400,-2514.480,-2451.190,-2738.44,64.4464,-2275.03,-2881.100,-4738.97000,...,-2257.890,-2582.420,-1699.10,-2295.30,306.483,209.4030,221.920,-4885.15,-2630.590,356.233
2841,2841,2842,-96.8233,-412.727,-1795.400,-2363.82,-2168.1900,-2162.68,-3155.740,-4416.11000,...,-3991.910,-2614.910,-2109.84,-2687.18,-2853.890,71.3402,-86.414,-5109.01,324.637,-4316.580
2842,2842,2843,-2364.6000,-155.592,-1422.090,-1713.40,465.6220,-2230.40,-3088.730,-5010.32000,...,-2484.500,-1756.080,-3820.43,-1988.23,433.852,291.8000,254.548,-4259.30,412.115,-1170.750
2843,2843,2844,-3004.6300,-1217.120,180.122,-1113.89,438.4180,-2442.51,-3210.560,-3237.74000,...,-3291.490,-2018.450,-3472.65,-3109.07,511.792,369.0970,276.948,-5574.51,298.739,460.419
2844,2844,2845,-2975.1000,-1129.790,463.748,-5355.40,193.5110,-2590.16,-3113.520,-2.38883,...,-3058.230,-2276.180,-3335.00,-2929.19,-1007.500,271.0580,307.997,-5453.33,307.495,417.124

In [25]:
ID=df_test['ID']
df_test.drop(['ID'],axis=1,inplace=True)

In [26]:
ID

0          1
1          2
2          3
3          4
4          5
        ...
2840    2841
2841    2842
2842    2843
2843    2844
2844    2845
Name: ID, Length: 2845, dtype: int64

In [27]:
y_test = model.predict(df_test)

In [28]:
y_test

array([1, 1, 1, ..., 3, 3, 3])

In [29]:
y_decoded = label_encoder.inverse_transform(y_test)
y_decoded

array(['forest', 'forest', 'forest', ..., 'impervious', 'impervious',
       'impervious'], dtype=object)

In [30]:
result = pd.DataFrame({
    'ID': ID,
    'class': y_decoded
})

In [31]:
result

        ID       class
0        1      forest
1        2      forest
2        3      forest
3        4      forest
4        5      forest
...    ...         ...
2840  2841  impervious
2841  2842  impervious
2842  2843  impervious
2843  2844  impervious
2844  2845  impervious

[2845 rows x 2 columns]

In [32]:
result.to_csv("submission.csv", index=False) #this file will appear under the output section of the right navbar. You need to submit this csv file